import { ColorTemplate, FontTemplate } from './types';

// Helper to make prompts stronger to force style/color changes
const enforce = (style: string) => 
  `Strictly transform the image into a ${style}. Replace the original colors and textures entirely. Redraw the subjects to match this art style. DO NOT add any new text.`;

export const COLOR_TEMPLATES: ColorTemplate[] = [
  {
    id: 'cloud-arch',
    name: 'Cloud Architecture',
    description: 'AWS/GCP Network Diagram',
    colors: ['#3b82f6', '#ffffff', '#94a3b8'],
    editPrompt: enforce('clean isometric vector art style with flat elements, distinct node connectors, and a white background'),
  },
  {
    id: 'cyberpunk',
    name: 'Neon Cyber',
    description: 'Futuristic high-contrast neon',
    colors: ['#00f3ff', '#ff00aa', '#0f0f1a'],
    editPrompt: enforce('Cyberpunk art style with high contrast neon glowing lines, wet street reflections, and a dark midnight atmosphere'),
  },
  {
    id: 'synthwave',
    name: 'Synthwave 80s',
    description: 'Retro sunset and grids',
    colors: ['#ff71ce', '#01cdfe', '#05ffa1'],
    editPrompt: enforce('80s Synthwave aesthetic with a retro wireframe grid, sunset gradients, and chrome textures'),
  },
  {
    id: 'noir',
    name: 'Film Noir',
    description: 'Dramatic black and white',
    colors: ['#000000', '#4a4a4a', '#ffffff'],
    editPrompt: enforce('Film Noir cinematic style with high contrast chiaroscuro lighting, dramatic silhouettes, and film grain'),
  },
  {
    id: 'blueprint',
    name: 'Tech Blueprint',
    description: 'Engineering schematic grid',
    colors: ['#1e3a8a', '#93c5fd', '#ffffff'],
    editPrompt: enforce('Technical architectural blueprint style with a deep blue grid background and precise white schematic lines'),
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    description: 'Bold Warhol style',
    colors: ['#ef4444', '#facc15', '#3b82f6'],
    editPrompt: enforce('Pop Art style with thick black outlines, Ben-Day dots, halftone patterns, and highly saturated solid colors'),
  },
  {
    id: 'risograph',
    name: 'Risograph Print',
    description: 'Grainy overlay print',
    colors: ['#ff0055', '#2a2aeb', '#ffe600'],
    editPrompt: enforce('Risograph printing style with grainy noise textures, slight color layer misalignment, and limited ink palette'),
  },
  {
    id: 'clay',
    name: 'Claymation',
    description: '3D Plasticine Model',
    colors: ['#ea580c', '#65a30d', '#22d3ee'],
    editPrompt: enforce('Stop-motion Claymation style with soft plasticine clay textures, fingerprint details, and rounded chunky shapes'),
  },
  {
    id: 'origami',
    name: 'Paper Origami',
    description: 'Folded paper craft',
    colors: ['#f8fafc', '#cbd5e1', '#64748b'],
    editPrompt: enforce('Origami Paper Craft style with sharp geometric folds, paper grain textures, and realistic drop shadows'),
  },
  {
    id: 'forest',
    name: 'Enchanted Forest',
    description: 'Magical nature tones',
    colors: ['#064e3b', '#d97706', '#fcd34d'],
    editPrompt: enforce('Enchanted Forest illustration style with deep mossy greens, glowing bioluminescent details, and organic textures'),
  },
  {
    id: 'pixel-art',
    name: '8-Bit Pixel',
    description: 'Retro game aesthetic',
    colors: ['#38b764', '#257179', '#29366f'],
    editPrompt: enforce('8-bit Pixel Art style with chunky blocky pixels, limited color palette, and no anti-aliasing'),
  },
  {
    id: 'low-poly',
    name: 'Low Poly',
    description: 'Geometric 3D mesh',
    colors: ['#6366f1', '#a855f7', '#ec4899'],
    editPrompt: enforce('Low Poly 3D art style with sharp geometric triangular facets, flat shading, and no smooth curves'),
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft artistic painting',
    colors: ['#ff9a9e', '#fad0c4', '#a18cd1'],
    editPrompt: enforce('Watercolor Painting style with wet-on-wet pigment bleeds, rough paper texture, and soft translucent edges'),
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    description: 'Japanese woodblock',
    colors: ['#c13c23', '#2f4f4f', '#eec9a1'],
    editPrompt: enforce('Traditional Japanese Ukiyo-e Woodblock print style with flat perspective, bold outlines, and muted natural colors'),
  },
  {
    id: 'sketch',
    name: 'Pencil Sketch',
    description: 'Hand-drawn graphite',
    colors: ['#ffffff', '#1f2937', '#9ca3af'],
    editPrompt: enforce('Graphite Pencil Sketch style with rough charcoal shading, visible hatch lines, and smudge effects on paper'),
  },
  {
    id: 'vintage',
    name: 'Classic Film',
    description: '1950s cinematic grain',
    colors: ['#78350f', '#d4c5a3', '#451a03'],
    editPrompt: enforce('Vintage 1950s photograph style with heavy sepia toning, film grain, vignetting, and scratches'),
  },
  {
    id: 'thermal',
    name: 'Thermal Vision',
    description: 'Infrared heat map',
    colors: ['#0000ff', '#ff0000', '#ffff00'],
    editPrompt: enforce('Thermal Infrared Camera style with a heat-map gradient spectrum ranging from cold blue to hot red and yellow'),
  },
  {
    id: 'stained-glass',
    name: 'Stained Glass',
    description: 'Church window mosaic',
    colors: ['#1e40af', '#b91c1c', '#f59e0b'],
    editPrompt: enforce('Stained Glass Mosaic style with vibrant translucent glass segments separated by thick black lead lines'),
  },
  {
    id: 'marker',
    name: 'Urban Sketch',
    description: 'Street art marker',
    colors: ['#ffd700', '#171717', '#ffffff'],
    editPrompt: enforce('Urban Sketch style with alcohol markers, bold varying-width ink outlines, and energetic coloring'),
  },
  {
    id: 'glitch',
    name: 'Glitch Art',
    description: 'Digital data corruption',
    colors: ['#ff00ff', '#00ffff', '#ffffff'],
    editPrompt: enforce('Digital Glitch Art style with RGB color channel splitting, pixel sorting, scanlines, and data moshing effects'),
  },
  {
    id: 'minimal',
    name: 'Swiss Modern',
    description: 'Clean and bold',
    colors: ['#ffffff', '#000000', '#ef4444'],
    editPrompt: enforce('Swiss Design Minimalist style with high contrast, large negative space, and flat solid colors'),
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard',
    description: 'Schoolroom drawing',
    colors: ['#14532d', '#ffffff', '#fca5a5'],
    editPrompt: enforce('Chalkboard Art style with white and pastel chalk textures on a dark green slate background'),
  },
  {
    id: 'pastel',
    name: 'Pastel Dream',
    description: 'Soft and candy-colored',
    colors: ['#fbcfe8', '#c7d2fe', '#ffffff'],
    editPrompt: enforce('Pastel Kawaii aesthetic with soft matte candy colors, low contrast, and dreamy diffuse lighting'),
  },
  {
    id: 'royal',
    name: 'Gilded Age',
    description: 'Luxury gold and velvet',
    colors: ['#ffd700', '#4a0e0e', '#171717'],
    editPrompt: enforce('Baroque Oil Painting style with deep shadows, rich velvet textures, and reflective gold leaf highlights'),
  },
];

export const FONT_TEMPLATES: FontTemplate[] = [
  {
    id: 'modern',
    name: 'Modern Sans',
    description: 'Clean and universal',
    fontFamily: 'font-sans',
    textStylePrompt: 'Render text in a BOLD, GEOMETRIC SANS-SERIF font. Clean and minimalist.',
  },
  {
    id: 'terminal',
    name: 'Dev Terminal',
    description: 'Code-like monospace',
    fontFamily: 'font-mono',
    textStylePrompt: 'Render text in a RETRO MONOSPACE font. Green-screen terminal style.',
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    description: 'Old school mechanical',
    fontFamily: 'font-typewriter',
    textStylePrompt: 'Render text in a VINTAGE TYPEWRITER font. Stamped ink look.',
  },
  {
    id: 'script',
    name: 'Casual Script',
    description: 'Friendly handwritten',
    fontFamily: 'font-script',
    textStylePrompt: 'Render text in a CASUAL ROUNDED HANDWRITING. Marker style.',
  },
  {
    id: 'elegant',
    name: 'Wedding',
    description: 'Formal calligraphy',
    fontFamily: 'font-elegant',
    textStylePrompt: 'Render text in ELABORATE CALLIGRAPHY. Flourishes and loops.',
  },
  {
    id: 'gothic',
    name: 'Blackletter',
    description: 'Ancient manuscript',
    fontFamily: 'font-gothic',
    textStylePrompt: 'Render text in GOTHIC BLACKLETTER. Old English medieval style.',
  },
  {
    id: 'comic',
    name: 'Comic Book',
    description: 'Loud and bold',
    fontFamily: 'font-comic',
    textStylePrompt: 'Render text in BOLD COMIC BOOK CAPITALS. Punchy and outlined.',
  },
  {
    id: 'game',
    name: 'Retro Console',
    description: '8-bit arcade text',
    fontFamily: 'font-pixel',
    textStylePrompt: 'Render text in BLOCKY 8-BIT PIXEL FONT. Arcade game style.',
  },
  {
    id: 'architect',
    name: 'Drafting Hand',
    description: 'Technical hand-drawn',
    fontFamily: 'font-architect',
    textStylePrompt: 'Render text in ARCHITECTURAL HAND LETTERING. Clean all-caps pencil style.',
  },
  {
    id: 'journal',
    name: 'Journalist',
    description: 'Natural handwriting',
    fontFamily: 'font-hand',
    textStylePrompt: 'Render text in MESSY NATURAL HANDWRITING. Quick scribbles.',
  },
  {
    id: 'cyber',
    name: 'Sci-Fi Display',
    description: 'Tech-inspired geometric',
    fontFamily: 'font-cyber',
    textStylePrompt: 'Render text in FUTURISTIC SCI-FI DISPLAY FONT. Angular and technical.',
  },
  {
    id: 'vintage',
    name: 'Editorial Serif',
    description: 'Elegant and traditional',
    fontFamily: 'font-vintage',
    textStylePrompt: 'Render text in HIGH-CONTRAST LUXURY SERIF. Fashion magazine style.',
  },
  {
    id: 'marker',
    name: 'Permanent Marker',
    description: 'Hand-drawn feel',
    fontFamily: 'font-marker',
    textStylePrompt: 'Render text in THICK PERMANENT MARKER. Bold and casual.',
  },
  {
    id: 'grotesk',
    name: 'Space Grotesk',
    description: 'Quirky and technical',
    fontFamily: 'font-grotesk',
    textStylePrompt: 'Render text in WIDE TECHNICAL SANS-SERIF. Brutalist style.',
  },
  {
    id: 'cinzel',
    name: 'Cinzel Decorative',
    description: 'Classic inscriptions',
    fontFamily: 'font-cinzel',
    textStylePrompt: 'Render text in CHISELED ROMAN SERIF. Classical stone carving style.',
  },
  {
    id: 'abril',
    name: 'Abril Fatface',
    description: 'Bold impact',
    fontFamily: 'font-abril',
    textStylePrompt: 'Render text in HEAVY BOLD DIDONE SERIF. Curvy and dramatic.',
  },
];